name: ItemCaster
version: ${version}
author: Phanisment
description: A rewrite version of ItemCaster that has same functionality, Cast skill using item.
main: ${main_class}
api-version: 1.20
depend:
- MythicMobs
- NBTAPI
softdepend:
- ItemsAdder
- Nexo
- Oraxen