 // Source code is unavailable, and was generated by the Fernflower decompiler.
package io.phanisment.itemcaster.menu.editor;

import java.util.ArrayList;
import java.util.List;

import io.phanisment.itemcaster.menu.editor.buttons.ItemEditorButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditAbilitiesButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditCustomModelDataButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditDisplayButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditDurabilityButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditFireResistanceButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditGlintButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditGroupButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditLoreButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditMaterialButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditMaxDurabilityButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditMaxStackButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditModelItemButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditRarityButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditTemplateButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditTrimButton;
import io.phanisment.itemcaster.menu.editor.buttons.EditUnbreakableButton;

public final class ItemEditorButtons {
	private final List<ItemEditorButton> BUTTONS = new ArrayList<>();

	public void reload() {
		new EditMaterialButton();
		new EditCustomModelDataButton();
		new EditTemplateButton();
		new EditTrimButton();
		new EditGroupButton();
		new EditDisplayButton();
		new EditLoreButton();
		new EditModelItemButton();
		new EditGlintButton();
		new EditDurabilityButton();
		new EditMaxDurabilityButton();
		new EditMaxStackButton();
		new EditFireResistanceButton();
		new EditUnbreakableButton();
		new EditAbilitiesButton();
		new EditRarityButton();
	}

	public void add(ItemEditorButton button) {
		BUTTONS.add(button);
	}

	public List<ItemEditorButton> buttons() {
		return BUTTONS;
	}
}